version "3"
services:
    browser:
        image: registry.cn-hangzhou.aliyuncs.com/xiayu/etcd-browser
        networks:
          vpcbr:
            ipv4_address: 172.16.238.11
        ports:
        - ""
        environment:
            ETCD_HOST: etcd
            ETCD_PORT: 2379
            ETCD_HTTPS: "TRUE"

    etcd:
      image: quay.io/coreos/etcd
      networks:
        vpcbr:
          ipv4_address: 172.16.238.10
      volumes:
      - etcd-data:/etcd-data
      command: >
        /usr/local/bin/etcd --data-dir=/etcd-data --name node1
        --initial-advertise-peer-urls http://172.16.238.10:2380 --listen-peer-urls http://0.0.0.0:2380
        --advertise-client-urls http://172.16.238.10:2379 --listen-client-urls http://0.0.0.0:2379
        --initial-cluster node1=http://172.16.238.10:2380

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 172.16.238.0/24

volumes:
  etcd-data: